[versions]
agp = "8.9.0"
compileSdk = "35"
targetSdk = "35"
minSdk = "21"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
material = { group = "com.google.android.material", name = "material", version = "1.12.0" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.0" }
activity = { group = "androidx.activity", name = "activity", version = "1.9.2" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.3.2" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
ext-junit = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.6.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
